services:
  postgres:
    image: postgres:18
    container_name: online_cinema_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT:-5432}:5432"

    volumes:
      - online_cinema_postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5


  postgres_test:
    image: postgres:18

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TEST_DB}

    ports:
      - "5433:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_TEST_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5


  mailpit:
    image: axllent/mailpit:latest

    ports:
      - "1025:1025"
      - "8025:8025"


  redis:
    image: redis:7-alpine

    ports:
      - "6379:6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5


  migrator:
    build:
      context: .

    command: alembic upgrade head

    env_file:
      - .env

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

    depends_on:
      postgres:
        condition: service_healthy


  api:
    build:
      context: .

    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --reload-dir /code/app

    volumes:
      - ./app:/code/app

    env_file:
      - .env

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

      SMTP_HOST: mailpit
      SMTP_PORT: 1025

      CELERY_BROKER_URL: redis://redis:6379/0

      S3_ENDPOINT_URL: http://minio:9000

    ports:
      - "8000:8000"

    depends_on:
      migrator:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      mailpit:
        condition: service_started

    develop:
      watch:
        - action: sync
          path: ./app
          target: /code/app

        - action: rebuild
          path: pyproject.toml

        - action: rebuild
          path: poetry.lock


  celery_worker:
    build:
      context: .

    command: >
      celery
      -A app.core.celery_app:celery_app
      worker
      --loglevel=INFO

    env_file:
      - .env

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

      CELERY_BROKER_URL: redis://redis:6379/0

    depends_on:
      migrator:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

    develop:
      watch:
        - action: sync+restart
          path: ./app
          target: /code/app

        - action: rebuild
          path: pyproject.toml

        - action: rebuild
          path: poetry.lock


  celery_beat:
    build:
      context: .

    command: >
      celery
      -A app.core.celery_app:celery_app
      beat
      --loglevel=INFO
      --schedule=/tmp/celerybeat-schedule

    env_file:
      - .env

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

      CELERY_BROKER_URL: redis://redis:6379/0

    depends_on:
      migrator:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

    develop:
      watch:
        - action: sync+restart
          path: ./app
          target: /code/app

        - action: rebuild
          path: pyproject.toml

        - action: rebuild
          path: poetry.lock

  tests:
    build:
      context: .

    command: poetry run pytest -v

    env_file:
      - .env

    environment:
      POSTGRES_TEST_HOST: postgres_test
      POSTGRES_TEST_PORT: 5432

    volumes:
      - ./app:/code/app

    depends_on:
      postgres_test:
        condition: service_healthy

    profiles:
      - test

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - online_cinema_minio_data:/data

  minio_init:
    image: minio/mc:latest
    depends_on:
      - minio
    environment:
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000
      $$S3_ACCESS_KEY
      $$S3_SECRET_KEY;
      do
        sleep 1;
      done;
      mc mb --ignore-existing local/$$S3_BUCKET_NAME;
      mc anonymous set download local/$$S3_BUCKET_NAME;
      exit 0;
      "


volumes:
  online_cinema_postgres_data:
  online_cinema_minio_data:
